"""Honeypot signature database.

Contains version-specific signatures for honeypot detection across different versions.
"""

from .versions import (
    # SSH Honeypots
    COWRIE_SIGNATURES,
    HERALDING_SSH_SIGNATURES,
    ENDLESSH_SIGNATURES,
    SSHESAME_SIGNATURES,
    BLACKNET_SIGNATURES,
    KOJONEY_SIGNATURES,
    # SMB/FTP Honeypots
    DIONAEA_SIGNATURES,
    # ICS/SCADA Honeypots
    CONPOT_SIGNATURES,
    GASPOT_SIGNATURES,
    GRIDPOT_SIGNATURES,
    HONEYPLC_SIGNATURES,
    # Elasticsearch Honeypots
    ELASTICPOT_SIGNATURES,
    # SMTP/Email Honeypots
    MAILONEY_SIGNATURES,
    HERALDING_MAIL_SIGNATURES,
    # Database Honeypots
    MONGODB_HONEYPOT_SIGNATURES,
    MYSQL_HONEYPOT_SIGNATURES,
    POSTGRESQL_HONEYPOT_SIGNATURES,
    REDIS_HONEYPOT_SIGNATURES,
    # Web/HTTP Honeypots
    HTTP_HONEYPOT_SIGNATURES,
    HELLPOT_SIGNATURES,
    WORDPOT_SIGNATURES,
    GLASTOPF_SIGNATURES,
    SHOCKPOT_SIGNATURES,
    # Telnet Honeypots
    TELNET_HONEYPOT_SIGNATURES,
    MTPOT_SIGNATURES,
    # RDP Honeypots
    RDP_HONEYPOT_SIGNATURES,
    # CVE-Specific Honeypots
    LOG4POT_SIGNATURES,
    CITRIX_HONEYPOT_SIGNATURES,
    CISCOASA_HONEYPOT_SIGNATURES,
    SPRING4SHELL_SIGNATURES,
    # Multi-Service Frameworks
    OPENCANARY_SIGNATURES,
    QEEQBOX_SIGNATURES,
    ARTILLERY_SIGNATURES,
    FAPRO_SIGNATURES,
    TPOT_SPECIFIC_SIGNATURES,
    TPOT_24_SIGNATURES,
    # Protocol-Specific
    VNC_HONEYPOT_SIGNATURES,
    SIP_HONEYPOT_SIGNATURES,
    # Fingerprinting
    HASSH_FINGERPRINTS,
    HONEYD_SIGNATURES,
)

__all__ = [
    "COWRIE_SIGNATURES",
    "HERALDING_SSH_SIGNATURES",
    "ENDLESSH_SIGNATURES",
    "SSHESAME_SIGNATURES",
    "BLACKNET_SIGNATURES",
    "KOJONEY_SIGNATURES",
    "DIONAEA_SIGNATURES",
    "CONPOT_SIGNATURES",
    "GASPOT_SIGNATURES",
    "GRIDPOT_SIGNATURES",
    "HONEYPLC_SIGNATURES",
    "ELASTICPOT_SIGNATURES",
    "MAILONEY_SIGNATURES",
    "HERALDING_MAIL_SIGNATURES",
    "MONGODB_HONEYPOT_SIGNATURES",
    "MYSQL_HONEYPOT_SIGNATURES",
    "POSTGRESQL_HONEYPOT_SIGNATURES",
    "REDIS_HONEYPOT_SIGNATURES",
    "HTTP_HONEYPOT_SIGNATURES",
    "HELLPOT_SIGNATURES",
    "WORDPOT_SIGNATURES",
    "GLASTOPF_SIGNATURES",
    "SHOCKPOT_SIGNATURES",
    "TELNET_HONEYPOT_SIGNATURES",
    "MTPOT_SIGNATURES",
    "RDP_HONEYPOT_SIGNATURES",
    "LOG4POT_SIGNATURES",
    "CITRIX_HONEYPOT_SIGNATURES",
    "CISCOASA_HONEYPOT_SIGNATURES",
    "SPRING4SHELL_SIGNATURES",
    "OPENCANARY_SIGNATURES",
    "QEEQBOX_SIGNATURES",
    "ARTILLERY_SIGNATURES",
    "FAPRO_SIGNATURES",
    "TPOT_SPECIFIC_SIGNATURES",
    "TPOT_24_SIGNATURES",
    "VNC_HONEYPOT_SIGNATURES",
    "SIP_HONEYPOT_SIGNATURES",
    "HASSH_FINGERPRINTS",
    "HONEYD_SIGNATURES",
]
